server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ascend
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    # set `show-sql` to true if you want to see SQL queries showing up on the console
    show-sql: true
  main:
    web-application-type: servlet